### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Caddi1971** [datorama/zabbix_rds_template#2]
Hi,
I've the same Problem with Zabbix Version 3.0.2
I use the DB Instance Name and get on Zabbix Frontend and withe the console:
File "./rds_stats.py", line 77, in
average = res[-1]["Average"] # last item in result set
IndexError: list index out of range

Boto Version is 2.39.0

I hope you can help me.

**Comment by efic1** [comment]
Hi,
Seems like the DB instance name was not found. which AWS region are you using? if it's different than us-east-1 you'll need to provide it in either the template or host macro ({$REGION}). I've just updated the template to include that.

Efi

**Comment by Caddi1971** [comment]
Hi,
we use the the "eu-central-1".
And i had changed the script in the following lines:
#get the region
if (options.region == None):
    options.region = 'eu-central-1'

**Comment by efic1** [comment]
No need to change the script, see my notes around the {$REGION} macro in the template
