### ISSUE TITLE
Not getting any data on zabbix

### ISSUE THREAD

**Issue by pratapsingh** [datorama/zabbix_rds_template#3]
I did setup as per the readme but no data reported to zabbix.
On Manually running the script after giving all the information i get below error:

average = res[-1]["Average"] # last item in result set
IndexError: list index out of range

After troubleshooting further I found out it is not getting any data from cloudwatch conn.get_metric_statistics. However I have given everything including region. IAM user have access to cloudwatch as well.

**Update**

I got this working now. Thanks

**Comment by tbjornli** [comment]
Hi @pratapsingh, how did you get it working, I'm experiencing the same issue.

**Comment by tbjornli** [comment]
I found the problem, it was related to the instance-id.

You need to use the instance name and not the resource which I used in the beginning.
The instance id is the name you first see when entering the RDS instance page. It's also the first part of the endpoint: **mydatabase**.xxxxxxxxxx.eu-west-1.rds.amazonaws.com

Use this instance id as your hostname when adding a new host and you should be fine.

**Comment by anup1384** [comment]
Hi,
I am not able to do monitor of AWS RDS ( Seoul region ) parameters in zabbix ( Singapore region ) for different region RDS instance.
But able to do monitoring with same region RDS instance.
Error- Received value [Traceback (most recent call last): File "/usr/lib/zabbix/externalscripts/rds_stats.py", line 73, in <module> average = res[-1]["Average"] # last item in result setIndexError: list index out of range] is not suitable for value type [Numeric (float)]

Please check the issue and share some solutions.

**Comment by imansilla** [comment]
Hi, someone please tell me if any one made it work.
thanks, Regards!

**Comment by dartua** [comment]
Hi,

I'v done like in README.md and it works perfect for me.
Did you go through all steps from manual?
Did you run the script manually?

**Comment by anup1384** [comment]
Yes get the same error as i mentioned there.

________________________________

**Comment by dartua** [comment]
Hi anup1384 ,

I've just created a new RDS instance in another region and it works! 
Maybe you made typo or something like that. 
Did you fill correct field REGION?
For example Asia Pacific (Singapore): ap-southeast-1,
Asia Pacific (Seoul): ap-northeast-2 
Another reason might be you added template and forgot to change REGION field.

**Comment by KHiis** [comment]
We have fixed the issues that you guys are having and is reported under a PR https://github.com/datorama/zabbix_rds_template/pull/4

**Comment by efic1** [comment]
PR #4 was approved and merged.
