### ISSUE TITLE
DBInstanceIdentifier is required

### ISSUE THREAD

**Issue by charlotattard** [datorama/zabbix_rds_template#7]
When I am executing the python script, the following error is being outputted. rds_stats.py: error: -i DBInstanceIdentifier is required. I have setup the script and gave it execute rights. I also have imported the template and assigned it to the correct host.

Can you please help ?

Thanks,

**Comment by asaf-david** [comment]
same issue, please help!

**Comment by efic1** [comment]
Please make sure you have the following configured:

1. set the right AWS region in the template's macro section {$REGION}
2. Attach the template to the relevant hosts. 
3. The zabbix host name must match the RDS DB Instance host name

See the details here:

https://github.com/datorama/zabbix_rds_template/blob/master/README.md

**Comment by marquesmatheus** [comment]
I've set it up the region on macro template's section, created a host with same name as rds db instance and attached the template to this host... and nothing's happens. Could you help me?

**Comment by carobeto** [comment]
@marquesmatheus 
I did it to work.
Go to external_scripts as root and execute the script to see the errors how "zabbix" user sees.
If you need help, post the errors.

**Comment by marquesmatheus** [comment]
@carobeto thx man! i wasn't with root account.
